### ISSUE TITLE
fix: fuse_notifier field references fuser on Windows — clippy broken since #89 follow-up

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/mntrs#93]
## Symptom

CI - Windows clippy job fails on every commit since 560e284:

```
error[E0433]: cannot find module or crate \`fuser\` in this scope
  --> src/lib.rs:407:51
   |
407 |     pub(crate) fuse_notifier: std::sync::OnceLock<fuser::Notifier>,
   |                                                   ^^^^^^ use of unresolved module or unlinked crate \`fuser\`

error[E0433]: cannot find module or crate \`fuser\` in this scope
  --> src\lib.rs:3837:42
3837 |             let _ = notifier.inval_inode(fuser::INodeNo(_ino), 0, -1);

error[E0433]: cannot find module or crate \`fuser\` in this scope
  --> src\lib.rs:1022:36
1022 | pub fn set_fuse_notifier(notifier: fuser::Notifier) {

error[E0433]: cannot find module or crate \`fuser\` in this scope
  --> src\lib.rs:1026:49
1026 | static FUSE_NOTIFIER: once_cell::sync::OnceCell<fuser::Notifier> = once_cell::sync::OnceCell::new();
```

## Root cause

Commit 560e284 (fix(write): invalidate FUSE kernel attr cache after each write — #89 follow-up) added a `fuse_notifier: OnceLock<fuser::Notifier>` field to `MntrsFs` plus two free functions (`set_fuse_notifier`, `FUSE_NOTIFIER` static) and a use site in the write handler (`notifier.inval_inode(fuser::INodeNo(_ino), 0, -1)`).

None of these are gated with `#[cfg(unix)]`. The `fuser` crate is Unix-only under `[target.'cfg(unix)'.dependencies]` in Cargo.toml (alongside the existing fuser-0.17 dep that was already unix-only). On Windows the field type, function signatures, and call site all reference a crate that doesn't exist.

## Why CI didn't catch it earlier

- Windows clippy job has been failing on every commit since 8d35fd2b (June 19 morning), but the CI pipeline didn't surface this as a hard failure for the main branch because... actually it did — `CI - Windows` shows failure for every commit going back to 8d35fd2b. Earlier commits (e.g. 31932ff0 on June 17) passed. The regression was masked because the failing CI job doesn't gate merges (it should, but the workflow config may not have required it).

## Fix

Gate every `fuser::` reference on unix:

```rust
#[cfg(not(windows))]
pub(crate) fuse_notifier: std::sync::OnceLock<fuser::Notifier>,
```

```rust
#[cfg(not(windows))]
pub fn set_fuse_notifier(notifier: fuser::Notifier) { ... }

#[cfg(not(windows))]
static FUSE_NOTIFIER: once_cell::sync::OnceCell<fuser::Notifier> = once_cell::sync::OnceCell::new();
```

The `notifier.inval_inode(...)` call site is in the FUSE write handler which is already in a `#[cfg(not(windows))]` block (it's inside the unix-only `impl Filesystem for MntrsFs` impl) — verify and add the gate if not.

## Suggested verification

1. Add the gates.
2. Build on Linux + run `cargo build --target x86_64-pc-windows-gnu` (or let CI run) to confirm Windows clippy passes.
3. Re-run all existing tests to ensure no behavioral regression.

## Related

This is the same class of bug as #59 (Windows clippy break from `write_at`). The pattern: opendal/fuser APIs that are Unix-only get referenced from `src/lib.rs` without `#[cfg(unix)]`. A lint rule or pre-commit check that greps `fuser::` references and verifies they're inside a `#[cfg(unix)]` block could catch these systematically.

Blocks: making `CI - Windows` green again.

**Comment by dyrnq** [comment]
Fixed by 866dcf4. All 5 fuser::Notifier / fuser::INodeNo references are now gated #[cfg(not(windows))]:

  src/lib.rs:413  — pub(crate) fuse_notifier field
  src/lib.rs:1032 — set_fuse_notifier fn
  src/lib.rs:1037 — FUSE_NOTIFIER static
  src/lib.rs:3855 — notifier.inval_inode(...) call site in write()
  src/lib.rs:5224 — MntrsFs::new_test_fs initializer

cargo build --release on Linux still passes; 17/17 bug_regression tests pass. Push to retrigger Windows clippy.
