### ISSUE TITLE
fix: do_write uses Unix-only write_at, breaks Windows build (regression from #12)

### ISSUE THREAD

**Issue by dyrnq** [dyrnq/mntrs#59]
## Symptom

CI `CI - Windows` job fails at the **Clippy** step:

```
error[E0599]: no method named `write_at` found for mutable reference `&mut std::fs::File` in the current scope
  --> src\lib.rs:5213:11
   |
5213 |         f.write_at(data, offset)?;
   |           ^^^^^^^^
```

## Root cause

Issue #12 changed `do_write` from `seek + write_all` to `write_at`:

```rust
use std::os::unix::fs::FileExt;
f.write_at(data, offset)?;
```

`std::os::unix::fs::FileExt` is **Unix-only**. On Windows, the equivalent is `std::os::windows::fs::FileExt` (a separate trait, with the same method name but different method signature — it doesn't take an offset). The compile failure blocks the entire Windows build.

## Suggested fix

Either:

A) Gate the call site:
```rust
#[cfg(unix)]
use std::os::unix::fs::FileExt;
#[cfg(windows)]
use std::os::windows::fs::FileExt;
f.write_at(data, offset)?;
```

Both traits define `write_at` but the Windows signature differs (no offset). The simplest portable version is to keep `seek + write_all` on Windows and only use `write_at` on Unix.

B) Add `#[cfg(unix)]` to the whole `do_write` body change (revert to `seek + write_all` on Windows, keep `write_at` on Unix for the syscall-savings win).

C) Use a portable helper that abstracts the platform difference.

## Reproduction

```sh
cargo build -p mntrs --target x86_64-pc-windows-gnu
```

## Linked run

- https://github.com/dyrnq/mntrs/actions/runs/27661899071 (CI - Windows, 1m55s, failed at Clippy)

## Related

- #12 (the change that introduced this)

**Comment by dyrnq** [comment]
Fixed by issue #60's revert. src/lib.rs:5540-5541 now uses f.seek(SeekFrom::Start(offset)) + f.write_all(data) instead of f.write_at — both std::io::Write methods are cross-platform, so the Windows CI clippy job no longer fails with 'no method named write_at'.
